# Generated by Django 2.2.7 on 2019-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDjango',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
