# Generated by Django 2.2.7 on 2019-11-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDjango2',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(max_length=45)),
            ],
        ),
    ]
