# Generated by Django 2.2.7 on 2019-11-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0002_userdjango2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDjango2',
        ),
        migrations.AddField(
            model_name='userdjango',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
