# Generated by Django 2.2.7 on 2019-12-01 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0003_auto_20191130_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('department', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id_dose', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id_record', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kioskoapp.MedicalRecord')),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=2)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bloodtype', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSignsMeasure',
            fields=[
                ('id_vs', models.IntegerField(primary_key=True, serialize=False)),
                ('ecg', models.CharField(max_length=20)),
                ('bloodpressure', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('id_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskoapp.MedicalRecord')),
            ],
        ),
    ]
