# Generated by Django 2.2.7 on 2019-12-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0004_doctor_dose_medicalrecord_user_vitalsignsmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dose',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dose',
            name='nursename',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
