# Generated by Django 2.2.7 on 2019-12-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0005_auto_20191201_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='id_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kioskoapp.Doctor'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
