# Generated by Django 2.2.7 on 2019-12-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0006_auto_20191201_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_record',
        ),
        migrations.DeleteModel(
            name='UserDjango',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='bloodtype',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lastname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='phone',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
