# Generated by Django 2.2.7 on 2019-12-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0007_auto_20191201_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='id_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kioskoapp.MedicalRecord'),
        ),
    ]
