# Generated by Django 2.2.7 on 2019-12-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0009_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='capacidad',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
