# Generated by Django 2.2.7 on 2019-12-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapp', '0010_record_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
